services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2026.1.3
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ../themes:/config/themes
    ports:
      - "8123:8123"
